name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install node dependencies
        run: npm install

      - name: Build extension
        run: npm run build:chrome
